---
- name: playbook tags
  hosts: [web_servers]
  gather_facts: no
  
  become: yes
  become_method: sudo

  tasks:
    - name: Update package cache
      tags: update
      apt:
        update_cache: yes

    - name: Install nginx, mariadb-server
      tags: install, always
      apt:
        name:  "{{item.package_name }}"
        state: "{{item.package_state}}"
      loop:
        - { package_name: "nginx", package_state: "latest" }
        - { package_name: "mariadb-server", package_state: "latest" } 
      
      # loop:
      #   - nginx
      #   - mariadb-server
          