---
- name: playbook tags
  hosts: [web_servers]
  
  become: yes
  become_method: sudo

  tasks:
    - name: Update package cache
      tags: update
      apt:
        update_cache: yes

    # - name: Install nginx
    #   apt:
    #     name:  "nginx "
    #     state: "latest"
    #   when: ansible_facts['distribution'] == "Ubuntu"
    
    # - name: Install httpd
    #   apt: 
    #     name: "httpd"
    #     state: latest
    #   when: ansible_facts['distribution'] == "CentOS"
      

    - name: Restart nginx
      shell: service nginx restart
      when: ansible_facts['distribution'] == "Ubuntu"
    
    - name: Restart httpd
      shell: service httpd restart
      when: ansible_facts['distribution'] == "CentOS"
