---
# tasks file for web

- name: Uninstall nginx
  apt:
    name: "{{ package_name }}"
    state: absent
  

- name: Install nginx
  apt:
    name: "{{ package_name }}"
    state: latest
  
  notify: Copy Files Handler