# tasks file for web

- name: Install nginx
  apt:
    name: "{{ package_name }}"
    state: latest
  register: package_result

- name: Copy files to host server
  copy:
    src: "roles/web/files/{{ item }}"
    dest: "~/files/{{ item }}"
  loop: "{{ files }}"
  when: package_result.changed 

- name: Restart nginx service
  shell: service nginx restart
  when: package_result.changed 